"""Pydantic models representing a company's full research profile.

A ``CompanyProfile`` is the top-level aggregate used throughout the
culture-matching pipeline:

  * Generated by ``generate_profiles.py`` (LLM-assisted research).
  * Parsed from Excel seed files by ``seed_from_generated_xlsx.py``.
  * Stored as a JSON blob in ``Company.profile_json`` with the 8 culture
    dimension columns promoted to indexed DB columns for fast scoring.
  * Scored against a user's culture preferences by ``score.py`` and
    ``similarity.py``.

Culture dimensions
------------------
Six numeric axes (0.0 – 1.0):
    empathy, creative_drive, adaptability, futuristic, harmony, data_orientation

Two categorical axes:
    work_environment — comma-separated tags (e.g. "collaborative, high-autonomy")
    pace             — one of: slow | moderate | fast | very-fast
                       Converted to a float via PACE_TO_FLOAT for vector math.
"""

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class Pace(Enum):
    """Ordered enum of work-pace labels.

    Used as the categorical type for ``CultureValues.pace``.  Values are
    mapped to the [0.0, 1.0] float range in ``PACE_TO_FLOAT`` so they can
    be included in cosine-similarity vectors alongside the numeric dimensions.
    """
    SLOW = "slow"
    MODERATE = "moderate"
    FAST = "fast"
    VERY_FAST = "very-fast"


# Maps each Pace level to an evenly-spaced float in [0, 1].
# Used by score.py and similarity.py for numeric proximity calculations.
PACE_TO_FLOAT: dict["Pace", float] = {
    Pace.SLOW: 0.0,
    Pace.MODERATE: 0.33,
    Pace.FAST: 0.66,
    Pace.VERY_FAST: 1.0,
}


class CompanyOverview(BaseModel):
    """High-level factual information about the company.

    Sourced from public records during LLM-assisted profile generation.
    All fields except ``name`` are optional to accommodate startups and
    companies where data is unavailable.
    """
    name: str
    founded: Optional[int] = None
    website: Optional[str] = None
    industry: Optional[str] = None
    size: Optional[str] = None                  # e.g. "enterprise", "mid-size", "startup"
    headquarters: Optional[str] = None
    ownership: Optional[str] = None             # e.g. "Public (NASDAQ: GOOGL)"
    revenue_est: Optional[str] = None
    headcount_est: Optional[str] = None


class Executive(BaseModel):
    name: str
    title: str
    linkedin_url: Optional[str] = None


class CultureValues(BaseModel):
    """The 8-dimension culture profile used for candidate matching.

    Narratives are prose summaries backfilled by ``backfill_culture_narratives.py``.
    Numeric dimensions are in [0.0, 1.0] — higher values represent stronger
    presence of that trait (e.g. empathy=1.0 means extremely people-first).

    The ``pace_float`` property converts the categorical ``pace`` string to a
    float so it can be included in cosine-similarity calculations.
    """
    culture_narrative_company: Optional[str] = None   # how the company describes its own culture
    culture_narrative_employees: Optional[str] = None  # how employees describe the culture
    core_values: list[str] = []
    work_environment: Optional[str] = None
    pace: str
    empathy: float                              # 0.0 – 1.0
    creative_drive: float
    adaptability: float
    futuristic: float
    harmony: float
    data_orientation: float

    @property
    def pace_float(self) -> Optional[float]:
        try:
            return PACE_TO_FLOAT[Pace(self.pace)]
        except (ValueError, KeyError):
            return None


class Compensation(BaseModel):
    new_grad_swe_total: Optional[str] = None
    mid_level_total: Optional[str] = None
    senior_total: Optional[str] = None
    base_range: Optional[str] = None
    equity_notes: Optional[str] = None
    bonus: Optional[str] = None
    levels: Optional[str] = None               # e.g. "L3 → L4 → L5 → L6 → L7"
    notes: Optional[str] = None


class InterviewProcess(BaseModel):
    difficulty: Optional[str] = None           # e.g. "Very High"
    process_overview: Optional[str] = None
    coding_focus: Optional[str] = None
    system_design: Optional[bool] = None
    behavioral: Optional[str] = None
    avg_rounds: Optional[int] = None
    timeline: Optional[str] = None             # e.g. "4–8 weeks"
    notes: Optional[str] = None


class RemotePolicy(BaseModel):
    policy: Optional[str] = None               # e.g. "Hybrid (3 days in office)"
    remote_friendly: Optional[str] = None      # e.g. "Limited", "Yes", "No"
    details: Optional[str] = None


class GlassdoorRatings(BaseModel):
    overall_rating: Optional[float] = None     # out of 5.0
    ceo_approval: Optional[str] = None         # e.g. "87%"
    recommend_to_friend: Optional[str] = None
    work_life_balance: Optional[float] = None
    compensation_score: Optional[float] = None
    culture_score: Optional[float] = None
    key_positives: Optional[str] = None
    key_negatives: Optional[str] = None
    source: Optional[str] = None


class NewsControversies(BaseModel):
    controversy_level: Optional[str] = None    # e.g. "High", "Medium", "Low"
    key_topics: Optional[str] = None
    recent_news: Optional[str] = None


class RecruitingContacts(BaseModel):
    key_programs: Optional[str] = None
    university_recruiting_url: Optional[str] = None
    general_jobs_url: Optional[str] = None
    linkedin_search_tip: Optional[str] = None
    recruiter_tip: Optional[str] = None


class TechStack(BaseModel):
    frontend: Optional[str] = None
    backend: Optional[str] = None
    infrastructure: Optional[str] = None
    data_ml: Optional[str] = None
    devtools_cicd: Optional[str] = None
    notable_oss: Optional[str] = None
    primary_languages: Optional[str] = None
    notes: Optional[str] = None


class InternshipProgram(BaseModel):
    program_exists: Optional[bool] = None
    program_name: Optional[str] = None
    duration_weeks: Optional[str] = None
    roles_available: Optional[str] = None
    weekly_comp_usd: Optional[str] = None
    return_offer_rate: Optional[str] = None    # e.g. "~85%"
    pipeline_to_fulltime: Optional[str] = None
    application_timeline: Optional[str] = None # e.g. "Aug–Jan"
    intern_headcount_est: Optional[str] = None
    notes: Optional[str] = None


class WorkforceSignals(BaseModel):
    warn_activity: Optional[str] = None
    warn_risk_level: Optional[str] = None      # e.g. "Medium"
    warn_analyst_note: Optional[str] = None
    reddit_glassdoor_themes: Optional[str] = None
    linkedin_signals: Optional[str] = None
    news_press_signals: Optional[str] = None
    overall_workforce_risk: Optional[str] = None
    signal_confidence: Optional[str] = None    # e.g. "Pattern-based"
    analyst_summary: Optional[str] = None


class CompanyProfile(BaseModel):
    """Top-level aggregate for a company's complete research profile.

    Serialized to ``Company.profile_json`` in the database.  The culture
    sub-object's fields are also promoted to indexed columns on the ``Company``
    table for efficient query-time scoring without JSON deserialization.
    """
    overview: CompanyOverview
    executives: list[Executive] = []
    culture: Optional[CultureValues] = None
    compensation: Optional[Compensation] = None
    interview: Optional[InterviewProcess] = None
    remote_policy: Optional[RemotePolicy] = None
    glassdoor: Optional[GlassdoorRatings] = None
    news: Optional[NewsControversies] = None
    recruiting: Optional[RecruitingContacts] = None
    tech_stack: Optional[TechStack] = None
    internship: Optional[InternshipProgram] = None
    workforce_signals: Optional[WorkforceSignals] = None
