"""Seed company profiles from the individual .xlsx files in company_profiles/.

Each file was generated by generate_profiles.py and has a two-column
label/value layout (column A = label, column B = value) with section
header rows whose cells are merged across A:B.

Run from the project root after applying migrations:

    alembic upgrade head
    python -m company_culture_LLM.seed_from_generated_xlsx

Requires DATABASE_URL in the environment (or a .env file).
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from dotenv import load_dotenv
load_dotenv()

import openpyxl
from flask import Flask
from model import db, Company
from company import (
    CompanyOverview, CompanyProfile, CultureValues, Compensation,
    Executive, GlassdoorRatings, InternshipProgram, InterviewProcess,
    NewsControversies, RecruitingContacts, RemotePolicy, TechStack,
    WorkforceSignals,
)
from company_culture_LLM.store import upsert_company

ROOT = Path(__file__).resolve().parent.parent
COMPANY_PROFILES = ROOT / "company_profiles"

SECTION_NAMES = {
    "COMPANY OVERVIEW",
    "EXECUTIVE LEADERSHIP",
    "CULTURE & VALUES",
    "COMPENSATION",
    "INTERVIEW PROCESS",
    "REMOTE / HYBRID POLICY",
    "GLASSDOOR / EMPLOYEE RATINGS",
    "RECENT NEWS & CONTROVERSIES",
    "RECRUITING & CONTACTS",
    "TECH STACK",
    "INTERNSHIP PROGRAM",
    "WORKFORCE SIGNALS",
}


# ---------------------------------------------------------------------------
# xlsx reader
# ---------------------------------------------------------------------------

def _read_sections(path: Path) -> dict[str, list[tuple[str, str]]]:
    """Read a generated company profile xlsx into section → [(label, value)] map."""
    wb = openpyxl.load_workbook(str(path), read_only=True)
    ws = wb.active

    sections: dict[str, list[tuple[str, str]]] = {}
    current: str | None = None

    for row in ws.iter_rows(values_only=True):
        col_a = row[0]
        col_b = row[1] if len(row) > 1 else None

        if col_a is None:
            continue

        label = str(col_a).strip()
        upper = label.upper()

        # Section header: col A matches a known section name, col B is empty
        if upper in SECTION_NAMES and not col_b:
            current = upper
            sections[current] = []
            continue

        # Skip the title row
        if upper == "COMPANY PROFILE":
            continue

        if current is not None and label:
            value = str(col_b).strip() if col_b is not None else ""
            sections[current].append((label, value))

    wb.close()
    return sections


def _kv(rows: list[tuple[str, str]]) -> dict[str, str]:
    """Convert a list of (label, value) pairs to a flat label → value dict."""
    return {label: value for label, value in rows}


# ---------------------------------------------------------------------------
# Type helpers
# ---------------------------------------------------------------------------

def _safe_float(val: str) -> float | None:
    """Parse a string to float, returning None on empty or invalid input."""
    if not val:
        return None
    try:
        return float(val)
    except ValueError:
        return None


def _safe_int(val: str) -> int | None:
    """Extract the first integer from a string (e.g. '~250' → 250), or None."""
    if not val:
        return None
    m = re.search(r"\d+", val)
    return int(m.group()) if m else None


def _safe_bool(val: str) -> bool | None:
    """Parse a Yes/No cell value to bool.  Returns None for empty strings."""
    if not val:
        return None
    return val.strip().lower().startswith("y")


def _glassdoor_rating(val: str) -> float | None:
    """Extract a decimal rating like '4.2 / 5.0' from a Glassdoor cell, or None."""
    if not val:
        return None
    m = re.search(r"\d+\.\d+", val)
    return float(m.group()) if m else None


# ---------------------------------------------------------------------------
# Section parsers  (labels match build_xlsx in generate_profiles.py)
# ---------------------------------------------------------------------------

def _parse_overview(rows: list[tuple[str, str]]) -> CompanyOverview:
    kv = _kv(rows)
    return CompanyOverview(
        name=kv.get("Name") or "Unknown",
        founded=_safe_int(kv.get("Founded", "")),
        website=kv.get("Website") or None,
        industry=kv.get("Industry") or None,
        size=kv.get("Size") or None,
        headquarters=kv.get("Headquarters") or None,
        ownership=kv.get("Ownership") or None,
        revenue_est=kv.get("Revenue (est.)") or None,
        headcount_est=kv.get("Headcount (est.)") or None,
    )


def _parse_executives(rows: list[tuple[str, str]]) -> list[Executive]:
    """Executives are stored as 'Executive N — Name / Title / LinkedIn URL' rows."""
    by_index: dict[int, dict[str, str]] = {}
    for label, value in rows:
        m = re.match(r"Executive (\d+) — (.+)", label)
        if not m:
            continue
        idx = int(m.group(1))
        field = m.group(2)
        by_index.setdefault(idx, {})[field] = value

    execs = []
    for idx in sorted(by_index):
        d = by_index[idx]
        name = d.get("Name", "").strip()
        if not name:
            continue
        execs.append(Executive(
            name=name,
            title=d.get("Title", "").strip(),
            linkedin_url=d.get("LinkedIn URL") or None,
        ))
    return execs


def _parse_culture(rows: list[tuple[str, str]]) -> CultureValues | None:
    kv = _kv(rows)
    # Required numeric fields — skip section entirely if all missing
    empathy = _safe_float(kv.get("Empathy (0.0\u20131.0)", ""))
    if empathy is None:
        return None
    return CultureValues(
        culture_narrative_company=kv.get("Culture Narrative (Company Says)") or None,
        culture_narrative_employees=kv.get("Culture Narrative (Employees Say)") or None,
        core_values=[v.strip() for v in kv.get("Core Values", "").split(",") if v.strip()],
        work_environment=kv.get("Work Environment") or None,
        pace=kv.get("Pace") or "moderate",
        empathy=empathy,
        creative_drive=_safe_float(kv.get("Creative Drive (0.0\u20131.0)", "")) or 0.0,
        adaptability=_safe_float(kv.get("Adaptability (0.0\u20131.0)", "")) or 0.0,
        futuristic=_safe_float(kv.get("Futuristic (0.0\u20131.0)", "")) or 0.0,
        harmony=_safe_float(kv.get("Harmony (0.0\u20131.0)", "")) or 0.0,
        data_orientation=_safe_float(kv.get("Data Orientation (0.0\u20131.0)", "")) or 0.0,
    )


def _parse_compensation(rows: list[tuple[str, str]]) -> Compensation:
    kv = _kv(rows)
    return Compensation(
        new_grad_swe_total=kv.get("New Grad SWE Total") or None,
        mid_level_total=kv.get("Mid-Level Total") or None,
        senior_total=kv.get("Senior Total") or None,
        base_range=kv.get("Base Range") or None,
        equity_notes=kv.get("Equity Notes") or None,
        bonus=kv.get("Bonus") or None,
        levels=kv.get("Levels") or None,
        notes=kv.get("Notes") or None,
    )


def _parse_interview(rows: list[tuple[str, str]]) -> InterviewProcess:
    kv = _kv(rows)
    return InterviewProcess(
        difficulty=kv.get("Difficulty") or None,
        process_overview=kv.get("Process Overview") or None,
        coding_focus=kv.get("Coding Focus") or None,
        system_design=_safe_bool(kv.get("System Design (Yes/No)", "")),
        behavioral=kv.get("Behavioral") or None,
        avg_rounds=_safe_int(kv.get("Avg Rounds", "")),
        timeline=kv.get("Timeline") or None,
        notes=kv.get("Notes") or None,
    )


def _parse_remote(rows: list[tuple[str, str]]) -> RemotePolicy:
    kv = _kv(rows)
    return RemotePolicy(
        policy=kv.get("Policy") or None,
        remote_friendly=kv.get("Remote Friendly") or None,
        details=kv.get("Details") or None,
    )


def _parse_glassdoor(rows: list[tuple[str, str]]) -> GlassdoorRatings:
    kv = _kv(rows)
    return GlassdoorRatings(
        overall_rating=_glassdoor_rating(kv.get("Overall Rating (/ 5.0)", "")),
        ceo_approval=kv.get("CEO Approval") or None,
        recommend_to_friend=kv.get("Recommend to Friend") or None,
        work_life_balance=_safe_float(kv.get("Work-Life Balance", "")),
        compensation_score=_safe_float(kv.get("Compensation Score", "")),
        culture_score=_safe_float(kv.get("Culture Score", "")),
        key_positives=kv.get("Key Positives") or None,
        key_negatives=kv.get("Key Negatives") or None,
        source=kv.get("Source") or None,
    )


def _parse_news(rows: list[tuple[str, str]]) -> NewsControversies:
    kv = _kv(rows)
    return NewsControversies(
        controversy_level=kv.get("Controversy Level") or None,
        key_topics=kv.get("Key Topics") or None,
        recent_news=kv.get("Recent News") or None,
    )


def _parse_recruiting(rows: list[tuple[str, str]]) -> RecruitingContacts:
    kv = _kv(rows)
    return RecruitingContacts(
        key_programs=kv.get("Key Programs") or None,
        university_recruiting_url=kv.get("University Recruiting URL") or None,
        general_jobs_url=kv.get("General Jobs URL") or None,
        linkedin_search_tip=kv.get("LinkedIn Search Tip") or None,
        recruiter_tip=kv.get("Recruiter Tip") or None,
    )


def _parse_tech_stack(rows: list[tuple[str, str]]) -> TechStack:
    kv = _kv(rows)
    return TechStack(
        frontend=kv.get("Frontend") or None,
        backend=kv.get("Backend") or None,
        infrastructure=kv.get("Infrastructure") or None,
        data_ml=kv.get("Data / ML") or None,
        devtools_cicd=kv.get("DevTools / CI/CD") or None,
        notable_oss=kv.get("Notable OSS") or None,
        primary_languages=kv.get("Primary Languages") or None,
        notes=kv.get("Notes") or None,
    )


def _parse_internship(rows: list[tuple[str, str]]) -> InternshipProgram:
    kv = _kv(rows)
    return InternshipProgram(
        program_exists=_safe_bool(kv.get("Program Exists (Yes/No)", "")),
        program_name=kv.get("Program Name") or None,
        duration_weeks=kv.get("Duration (weeks)") or None,
        roles_available=kv.get("Roles Available") or None,
        weekly_comp_usd=kv.get("Weekly Comp (USD)") or None,
        return_offer_rate=kv.get("Return Offer Rate") or None,
        pipeline_to_fulltime=kv.get("Pipeline to Full-Time") or None,
        application_timeline=kv.get("Application Timeline") or None,
        intern_headcount_est=kv.get("Intern Headcount Est.") or None,
        notes=kv.get("Notes") or None,
    )


def _parse_workforce(rows: list[tuple[str, str]]) -> WorkforceSignals:
    kv = _kv(rows)
    return WorkforceSignals(
        warn_activity=kv.get("WARN Activity") or None,
        warn_risk_level=kv.get("WARN Risk Level") or None,
        warn_analyst_note=kv.get("WARN Analyst Note") or None,
        reddit_glassdoor_themes=kv.get("Reddit / Glassdoor Themes") or None,
        linkedin_signals=kv.get("LinkedIn Signals") or None,
        news_press_signals=kv.get("News / Press Signals") or None,
        overall_workforce_risk=kv.get("Overall Workforce Risk") or None,
        signal_confidence=kv.get("Signal Confidence") or None,
        analyst_summary=kv.get("Analyst Summary") or None,
    )


_SECTION_PARSERS = {
    "COMPENSATION":                  ("compensation",       _parse_compensation),
    "INTERVIEW PROCESS":             ("interview",          _parse_interview),
    "REMOTE / HYBRID POLICY":        ("remote_policy",      _parse_remote),
    "GLASSDOOR / EMPLOYEE RATINGS":  ("glassdoor",          _parse_glassdoor),
    "RECENT NEWS & CONTROVERSIES":   ("news",               _parse_news),
    "RECRUITING & CONTACTS":         ("recruiting",         _parse_recruiting),
    "TECH STACK":                    ("tech_stack",         _parse_tech_stack),
    "INTERNSHIP PROGRAM":            ("internship",         _parse_internship),
    "WORKFORCE SIGNALS":             ("workforce_signals",  _parse_workforce),
}


def parse_generated_xlsx(path: Path) -> CompanyProfile:
    """Parse a single generated company profile xlsx into a CompanyProfile."""
    sections = _read_sections(path)

    overview = _parse_overview(sections.get("COMPANY OVERVIEW", []))
    executives = _parse_executives(sections.get("EXECUTIVE LEADERSHIP", []))
    culture = _parse_culture(sections.get("CULTURE & VALUES", []))

    kwargs: dict = {"overview": overview, "executives": executives, "culture": culture}
    for section_key, (field, parser_fn) in _SECTION_PARSERS.items():
        rows = sections.get(section_key, [])
        if rows:
            kwargs[field] = parser_fn(rows)

    return CompanyProfile(**kwargs)


# ---------------------------------------------------------------------------
# App + seeder
# ---------------------------------------------------------------------------

def create_app() -> Flask:
    app = Flask(__name__)
    app.config["SQLALCHEMY_DATABASE_URI"] = os.environ["DATABASE_URL"]
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
    db.init_app(app)
    return app


def run_seed(verbose: bool = True) -> None:
    """Discover all .xlsx files in company_profiles/ and upsert them into the DB.

    Reports per-file insert/update/error status to stdout.  Rolls back and
    continues on per-file errors so one bad file doesn't abort the entire run.

    Args:
        verbose: Print per-file status lines (default True).  Set to False for
                 quieter CI/cron execution.
    """
    xlsx_files = sorted(COMPANY_PROFILES.glob("*.xlsx"))
    if not xlsx_files:
        print(f"No .xlsx files found in {COMPANY_PROFILES}")
        sys.exit(0)

    print(f"Found {len(xlsx_files)} file(s) in {COMPANY_PROFILES}\n")

    app = create_app()
    with app.app_context():
        seeded, updated, errors = 0, 0, 0
        for path in xlsx_files:
            try:
                profile = parse_generated_xlsx(path)
                name = profile.overview.name

                slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
                existing = Company.query.filter_by(slug=slug).first()

                upsert_company(profile)

                if existing:
                    updated += 1
                    if verbose:
                        print(f"  updated  {name}  ({path.name})")
                else:
                    seeded += 1
                    if verbose:
                        print(f"  inserted {name}  ({path.name})")
            except Exception as exc:
                errors += 1
                db.session.rollback()
                print(f"  ERROR {path.name}: {exc}")

        print(f"\nDone — {seeded} inserted, {updated} updated, {errors} errors.")


if __name__ == "__main__":
    run_seed()
